### ISSUE TITLE
no early media with Session Progress

### ISSUE THREAD

**Issue by usmanbaiga** [ptinovacao/asterisk-i#48]
Dear Team, 

asterisk is not sending out audio until the line is answered.
I do not see any RTP flowing out of asterisk while playing back an announcement with Playback (noanswer).

here is my dialplan

[noanswer_demo]
exten => s,1,Progress()
exten => s,n,Monitor(wav,testCall-${STRFTIME(${EPOCH},GMT+3,%C%y%m%d%H%M)})
<b>exten => s,n,Background(hello-world, n) ; ----> 1</b>
exten => s,n,WaitExten(1)
<b>exten => s,n(cont),Playback(hello-world, noanswer) ; ----> 2</b>
exten => s,n,Wait(1)
<b>exten => s,n,Playback(hello-world) ; ----> 3</b>
exten => s,n,Playback(demo-instruct)
exten => s,n,Playback(hello-world)
exten => s,n,Playback(demo-instruct)
exten => s,n,Hangup()

I am not hearing the 1st and 2nd prompts BUT the Monitor file contains all the prompts.

:::::::: Another observation ::::::::
Below is the Mime I am receiving and we are replying with SIP and not SIP-I message.
<i>
Content-Type:application/ISUP;base=itu-t92+;version=itu-t92+
Content-Disposition:signal;handling=required
Content-Transfer-Encoding:binary
</i>
i guess we are simply ignoring the *handling=required*

can you please guide me how can i solve these problems

<b>NOTE:</b>
all 51 patches applied

**Comment by asapage** [comment]
Hi,

Our setup concentrates the whole dialplan in one app, the WMSApp(), so it’s really different from yours.

Have you already activated the next parameter in sip.conf (added with patch: p012_chan_sip_isup)?
isupmimetype = application/ISUP\; base=nxv3\; version=itu-t92+

**Comment by usmanbaiga** [comment]
Hi asapage,

thanks for writing.
yes, i have this mime activated, since this is what I was receiving from other side
isupmimetype=application/ISUP;base=itu-t92+;version=itu-t92+

anywayz, I sorted out the early-media issue, my box was not recognizing Content-Type "without space" ;)

so I had to add a minor fix for that

if (!strcasecmp(line, "Content-Type: application/sdp") || !strcasecmp(line, "Content-Type:application/sdp"))

and

else if (!strncasecmp(line, "Content-Type: application/isup", 30) || !strncasecmp(line, "Content-Type:application/isup", 29))


can you please guide me how to make use of "isup_charge" and "isup_nocharge" messages.
